apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-case
  labels:
    app: hello-case
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-case
  template:
    metadata:
      labels:
        app: hello-case
    spec:
      containers:
      - name: hello-case
        image: gcr.io/halogen-episode-416211/hello-case:latest
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: hello-case-pvc
          mountPath: /application/log
      volumes:
      - name: hello-case-pvc
        persistentVolumeClaim:
          claimName: hello-case-pvc